version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/oneappstore
      - JDBC_DRIVER=org.postgresql.Driver
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key-here-please-change-in-production
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - GITHUB_REDIRECT_URI=http://localhost:3000/auth/github/callback
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oneappstore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 