services:
  - type: web
    name: oneappstore-api
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: JDBC_URL
        fromDatabase:
          name: oneappstore-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: oneappstore-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: oneappstore-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_REDIRECT_URI
        value: https://your-app-name.onrender.com/auth/github/callback
    autoDeploy: true

databases:
  - name: oneappstore-db
    plan: free
    ipAllowList: [] 